name: Feature Request
description: Suggest an idea or enhancement for this project
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...

  - type: textarea
    id: solution
    attributes:
      label: Describe the Solution You'd Like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe Alternatives You've Considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: dropdown
    id: device-compatibility
    attributes:
      label: Device Compatibility
      description: Is this feature specific to certain Tesy devices?
      options:
        - All devices
        - CN06 series only
        - Convectors only
        - Other (please specify in additional context)
        - Not device-specific

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important
        - Critical

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
